Repository github/rally, pull requests merged in 2020-08, with the labels that each got.

#92 Move license for visibility
  .github/README.md
  LICENSE
  package.json
Labels: bug

#95 fix spelling of "your"
  lib/RallyValidate.js
Labels: bug

#94 Remove 'master' branch references
  lib/RallyValidate.js
Labels: enhancement

#96 Add reviewer checklist
  .github/pull_request-template.md
Labels: documentation

#98 Adding dependabot
  .github/CODEOWNERS
  .github/dependabot.yml
  .github/workflows/auto-merge-depedabot.yml
Labels: dependencies, enhancement

#108 Remove project requirement
  .github/README.md
  lib/RallyValidate.js
  rally.yml
Labels: enhancement

#99 adding deploy
  .automation/log.sh
  .automation/upload-docker.sh
  .github/workflows/deploy-PROD.yml
  .github/workflows/deploy-RELEASE.yml
  .github/workflows/log.sh
  .github/workflows/stack-linter.yml
  Dockerfile
  docs/pullFromDockerHub.md
Labels: enhancement

#118 Rename auto-merge-depedabot.yml to auto-merge-depedabot.disabled
  .github/workflows/auto-merge-depedabot.disabled
Labels: infrastructure

#119 Add dependency PRs to 🧰 Maintenance group
  .github/release-drafter.yml
Labels: infrastructure
